### ISSUE TITLE
Ajax calls

### ISSUE THREAD

**Issue by zekenie** [dobtco/formbuilder#1]
Are they there by design or a relic from the initial use case? coffeescript file 326

**Comment by ajb** [comment]
a relic -- but i'm thinking we should provide some implementation guidance... it's not just as simple as sending everything up and hoping that it gets there. since we don't want for the server when adding a new field, we have to track new fields when they're first sent to the server and make sure they get updated with a proper ID once the response is returned.

that, or we can just remove `saveForm` entirely and leave it up to the developer.

**Comment by zekenie** [comment]
They'll have to implement on their own anyway, right? I suppose we could pass in certain save params to the constructor like path method and cb.

**Comment by ajb** [comment]
See what I've done with it now, and let me know if you have ideas for improvement.
