### ISSUE TITLE
FromBuilder Renders elements randomly .

### ISSUE THREAD

**Issue by laxmi-narayan-nitdgp** [dobtco/formbuilder#165]
I am using form builder lib. But somehow lib renders the elements randomly . rather than the order in which it was created. Does it default behavior of lib or it could be customized or if there is any fault from my side.

**Comment by smurfpandey** [comment]
The library will render the elements in the same order as the JSON that you bootstrap it with. Check your JSON array if it's getting randomized somewhere.

**Comment by SteveChurch** [comment]
They should be created in the order they are rendered on to the page. I have noticed that ordering does not work for me when changing the order because their if no specific option within the JSON/ Attributes to determine a display order so when I render mine they are in the initial order they fields were created with,. 

I will work on adding this feature or at least looking to see if it is mean to be within the library.

**Comment by laxmi-narayan-nitdgp** [comment]
Hi, Steve , I found the solution in the library itself . 
Once the payload is created by library . we should call function "sort" to arrange them.
This is in build function.
' fv_form.mainView.collection.sort();'
I am facing another issue , i will log once it gets confirmed.

**Comment by SteveChurch** [comment]
@laxmi-narayan-nitdgp 
Excellent, 

Thanks for the update.
