### ISSUE TITLE
Building a product on formbuilder

### ISSUE THREAD

**Issue by lukeholder** [dobtco/formbuilder#17]
I plan to build a standalone form builder application on formbuilder, and would like to contribute back to core and not make a fork. What are you thoughts around the follow additional features:
1. Page Break type in addition to the section type
2. Form Properties (options for the whole form not just the fields)
3. If / then definitions (if user selects an option, fields appear and disappear)

I have a bunch more but just want to get your thoughts.

**Comment by ajb** [comment]
Hey Luke, thanks for reaching out. I can't tell you how excited I am that you want to build an application on top of Formbuilder.

All of those features sound like things that would be great to have, and because of Formbuilder's architecture, you should be able to implement them without touching too much of the Formbuilder core. (i.e. for a page break, just fork and modify `fields/section_break.coffee`) Afterwards, send a PR and we'll discuss merging them into the main repo? 

for 2 and 3, maybe we should discuss adding a better API for registering form properties and field properties? Let me know if you have ideas, otherwise I'll put this on my list of todos.
