### ISSUE TITLE
Add HTML 5 Datalist Support 

### ISSUE THREAD

**Issue by rposborne** [dobtco/formbuilder#47]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

Would you be interested in adding this field to the core?

I will be more than happy to do a PR.

**Comment by ajb** [comment]
To be honest, I've never used this element before, and since it lacks IE9 and **Safari** support, I don't really think it's something we should encourage the use of. 

If you want to make a "plugin" that adds a datalist form field (just follow [this format](https://github.com/dobtco/formbuilder/blob/gh-pages/src/scripts/fields/address.coffee)), I'll be more than happy to link to it from the README.
